fix(Ghost): updateOffer if offerAlreadyExist
mangrovedao/mangrove-core pull request #32
Opened 2022-10-17 14:52 UTC by peterMangrove

2022-10-17 15:06 UTC, jkrivine requested changes

2022-10-17 15:06 UTC, jkrivine commented on src/toy_strategies/offer_maker/Ghost.sol
> +import {t_of_struct as packOffer} from "src/preprocessed/MgvOffer.post.sol";
you should not need this

2022-10-17 15:06 UTC, jkrivine commented on src/toy_strategies/offer_maker/Ghost.sol
> +      MGV.offerInfo(address(BASE), address(STABLE1), offerId1);
this is way too gas costly. You want to get the packed offer and offer detail and prune whatever info you want form the packed data.
```solidity
MgvStructs.OfferPacked offer = mgv.offers(address(BASE), address(STABLE1), offerId1);
MgvStructs.OfferDetailPacked detail = mgv.offerDetails(address(BASE), address(STABLE1), offerId1);
```
and then `offer.gives()` or `detail.gasreq()` to extract a specific field

2022-10-18 07:14 UTC, peterMangrove commented on src/toy_strategies/offer_maker/Ghost.sol
> +import {t_of_struct as packOffer} from "src/preprocessed/MgvOffer.post.sol";
Done

2022-10-18 07:14 UTC, peterMangrove commented on src/toy_strategies/offer_maker/Ghost.sol
> +      MGV.offerInfo(address(BASE), address(STABLE1), offerId1);
Done

2023-03-28 08:58 UTC, jkrivine approved these changes

2023-04-18 08:52 UTC, closed without merging