refactor: Simplify offer price match flow
mangrovedao/mangrove-core pull request #446
Opened 2023-08-14 12:46 UTC by espendk

Previously, `execute` checked that the offer to be executed had a sufficiently low price. If this wasn't the case, `"mgv/notExecuted"` was returned and used to tell the next recursive call to `internalMarketOrder` that the order was finished.

This flow was somewhat convoluted: The decision on which offers to execute was distributed between multiple functions, despite only the outermost of those actually needing it. And because of this, the execute-offer path of `internalMarketOrder` had two if-stmts just to make sure it **did not** handle an offer that shouldn't be executed.

This commit instead moves the check out one level to `internalMarketOrder` and `clean`. This simplifies the code of all involved functions and reduces gas usage.

The tradeoff is that the price check code is duplicated and that the caller of `execute` must ensure that the taker is not matched with an offer that is too expensive. However, this is seems acceptable as the duplicated code is a trivial function call and `execute` is `internal`.

2023-08-15 07:46 UTC, lnist commented on src/MgvOfferTaking.sol
>          /* note that internalMarketOrder may be called twice with same offerId, but in that case `proceed` will be false! */
update comment

2023-08-16 18:11 UTC, espendk commented on src/MgvOfferTaking.sol
>          /* note that internalMarketOrder may be called twice with same offerId, but in that case `proceed` will be false! */
removed in [c263db4](https://github.com/mangrovedao/mangrove-core/pull/446/commits/c263db4e477b936cc3db40f06b213bb91c413b5f)

2023-08-22 16:05 UTC, jkrivine requested changes

2023-08-22 16:05 UTC, jkrivine commented on src/MgvOfferTaking.sol
> +        /* If `proceed` is false, the taker has gotten its requested volume, no more offers match, or we have reached the end of the book, we conclude the market order. */
Remove mention to `proceed` also line 211

2023-08-23 00:45 UTC, espendk commented on src/MgvOfferTaking.sol
> +        /* If `proceed` is false, the taker has gotten its requested volume, no more offers match, or we have reached the end of the book, we conclude the market order. */
Addressed in [76f3afa](https://github.com/mangrovedao/mangrove-core/pull/446/commits/76f3afa0c8f42fd8459ad450a7b9651e7ccb1d1b)

2023-08-24 12:34 UTC, adhusson commented
@espendk I'm getting a feedback from @jkrivine saying that MgvReader does not do the price check in the market order!

2023-08-24 18:24 UTC, espendk commented
> @espendk I'm getting a feedback from @jkrivine saying that MgvReader does not do the price check in the market order!

Oh, there's a simulation of market order in `MgvReader` 😳 That'll need to be updated, but that's much broader than this PR. I suggest we add it to the `feat/ticks` task list.

2023-08-24 19:55 UTC, adhusson commented
Added to the TODO!

2023-08-24 19:55 UTC, adhusson commented
Added to the TODO!Added to the TODO!

2023-08-24 20:01 UTC, adhusson approved these changes
let's go

2023-08-25 06:07 UTC, merged