Audit/fixes
mangrovedao/mangrove-core pull request #70
Opened 2022-11-08 15:10 UTC by jkrivine

Fixing issues raised by security audit (detailed in the commits)

2022-11-10 12:01 UTC, lnist requested changes
Some small comments

2022-11-10 12:01 UTC, lnist commented on src/strategies/interfaces/IOrderLogic.sol
> +  ///@dev If new ttl is in the past of the current block, offer will renege on trade.
Maybe add timestamp: "current block timestamp"

2022-11-10 12:01 UTC, lnist commented on src/strategies/interfaces/IOrderLogic.sol
> +  ///@dev If new ttl is in the past of the current block, offer will renege on trade.
Replace "ttl" with expiry?

2022-11-10 12:01 UTC, lnist commented on src/strategies/MangroveOrder.sol
> +    mgvOrOwner(outbound_tkn, inbound_tkn, offerId)
// We also allow Mangrove to call this so that it can be used from, e.g., post-hooks.

2022-11-10 12:01 UTC, lnist commented on src/strategies/MangroveOrder.sol
> +        // partialFill => tko.makerWants < res.takerGot + res.fee
(sorry if you already answered this in another thread): makerWants input by the owner, right? It is not computed. So tko.makerWants could be 0 in which case we get an underflow in this unchecked calculation.

Should we stress that the invariant is _supposed_ to hold since tko.makerWants is _supposed_ to be before slippage? Should we have a "require"?

It is worse for "makerGives" because "residualGives" can become very high with underflow - making a really good offer for someone to grab.

2022-11-10 12:01 UTC, lnist commented on src/strategies/MangroveOrder.sol
> +    require(tko.expiryDate == 0 || tko.expiryDate >= block.timestamp, "mgvOrder/expired");
In __lastLook__ we use:
require(exp == 0 || block.timestamp <= exp, "mgvOrder/expired");

so just for readability I think we should use the same comparison.

2022-11-14 10:10 UTC, lnist requested changes

2022-11-14 10:10 UTC, lnist commented on src/strategies/MangroveOrder.sol
> +      // partialFill => tko.makerWants < res.takerGot + res.fee
remove "tko." from "tko.makerwants" in comment

2022-11-14 10:10 UTC, lnist commented on src/strategies/interfaces/IOrderLogic.sol
> +  ///@param slippageAmount if `fillWants` (buying) this is the amount of inbound tokens that must be substracted from `takerGives` to obtain the taker price before slippage. Else this is the amount o
Should we give an example of how to calculate slippageAmount given a wanted price?

2022-11-14 12:03 UTC, lnist approved these changes

2022-11-14 14:18 UTC, adhusson approved these changes
lgtm

2022-11-15 13:45 UTC, merged